# Generated by Django 5.1.3 on 2024-11-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_types',
            field=models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('EDUCATIONAL', 'EDUCATIONAL'), ('BUSINESS', 'BUSINESS')], default='PERSONAL', max_length=20),
        ),
    ]
