# Generated by Django 5.1.3 on 2024-11-30 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('account_number', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('currency', models.CharField(choices=[('NGN', 'NGN')], max_length=5)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_withdrawal_date', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_limit', models.DecimalField(decimal_places=2, default=1000000, max_digits=10)),
                ('maturity_date', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
