# Generated by Django 5.1.3 on 2024-12-02 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Loan_accounts',
        ),
        migrations.AlterModelOptions(
            name='loan_accounts',
            options={'verbose_name': 'Loan_account', 'verbose_name_plural': 'Loan_accounts'},
        ),
    ]
